// GENERATED CODE - DO NOT MODIFY BY HAND
// This file was generated by FlutterGen

import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

class AppLocalizations {
  AppLocalizations();

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const List<LocalizationsDelegate<dynamic>> localizationsDelegates =
      <LocalizationsDelegate<dynamic>>[
    delegate,
    GlobalMaterialLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
  ];

  static const List<Locale> supportedLocales = <Locale>[
    Locale('en'),
    Locale('id')
  ];

  // App
  String get appName => 'Productivity';

  // Navigation
  String get dashboard => 'Dashboard';
  String get statistics => 'Statistics';
  String get budget => 'Budget';
  String get search => 'Search';
  String get settings => 'Settings';

  // Profile
  String get profile => 'Profile';
  String get editProfile => 'Edit Profile';
  String get fullName => 'Full Name';
  String get email => 'Email';
  String get saveChanges => 'Save Changes';

  // Appearance
  String get appearance => 'Appearance';
  String get themeColor => 'Theme Color';
  String get language => 'Language';

  // Account
  String get account => 'Account';
  String get logout => 'Logout';
  String get logoutConfirm => 'Are you sure you want to logout?';
  String get cancel => 'Cancel';
  String get yes => 'Yes';

  // Notifications
  String get notifications => 'Notifications';
  String get dailyReminder => 'Daily Reminder';
  String get weeklyReminder => 'Weekly Reminder';

  // Security
  String get security => 'Security';
  String get enablePIN => 'Enable PIN';
  String get changePIN => 'Change PIN';
  String get enterPIN => 'Enter PIN';
  String get confirmPIN => 'Confirm PIN';
  String get pinNotMatch => 'PINs do not match';
  String get pinRequired => 'PIN is required';
  String get pinLength => 'PIN must be 4-6 digits';
  String get pinSetSuccess => 'PIN set successfully';
  String get pinWrong => 'Wrong PIN';

  // Backup & Export
  String get backupExport => 'Backup & Export';
  String get exportData => 'Export Data';
  String get exportCSV => 'Export as CSV';
  String get exportPDF => 'Export as PDF';
  String get exportSuccess => 'Data exported successfully';
  String get exportFailed => 'Export failed';
  String get permissionRequired => 'Storage permission required';
  String get noData => 'No data to export';

  // Support
  String get support => 'Support & Help';
  String get faq => 'FAQ';
  String get contactSupport => 'Contact Support';
  String get privacyPolicy => 'Privacy Policy';
  String get termsOfService => 'Terms of Service';

  // About
  String get about => 'About App';
  String get version => 'Version';
  String get developedBy => 'Developed by';

  // Messages
  String get profileUpdated => 'Profile updated successfully';
  String get required => 'Required';
  String get invalidAmount => 'Invalid amount';
  String get selectCategory => 'Select category';
  String get selectDate => 'Select date';

  // Search
  String get searchTransactions => 'Search transactions...';
  String get income => 'Income';
  String get expense => 'Expense';
  String get all => 'All';
  String get categories => 'Categories';
  String get total => 'Total';
  String get transactions => 'transactions found';
  String get noResults => 'No results found';

  // Transaction
  String get addTransaction => 'Add Transaction';
  String get edit => 'Edit';
  String get delete => 'Delete';
  String get deleteConfirm =>
      'Are you sure you want to delete this transaction?';
  String get category => 'Category';
  String get amount => 'Amount';
  String get date => 'Date';
  String get note => 'Note';
  String get save => 'Save';
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations());
  }

  @override
  bool isSupported(Locale locale) =>
      <String>['en', 'id'].contains(locale.languageCode);

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
